### ISSUE TITLE
feedback from Ben Tatman (SPB PhD student)

### ISSUE THREAD

**Issue by jkshenton** [CCP-NC/ccpnc-database#20]
In GitLab by @brownsp on Feb 10, 2021, 17:09

•	The landing page isn't especially useful, it might be useful to have a little more information about what the website is for, and some large buttons for deposition and access in the central region?

•	The search page looks much nicer, but the labels in the search table are not vertically centred.

•	On the results page there's a gap between Version and License. I don't know if this is intentional or if there's some information missing?

•	It might be nice to have the DOI on the results page too (especially when searching by DOI!)

•	If someone gives me an MRD number it's not immediately obvious how to find the record. It might be nice to add the ability to search by MRD (and this could be put on the landing page?)

•	For search by external database reference it might be nice to replace the "Database name" with a dropdown list (or some examples, like should I put ccdc, CCDC, cambridge crystallographic datacenter?)

•	The unit cell formula looks nice on the search page but it might be useful to have this on the item results page too?

•	The calculation details can't be selected or held open which is a bit annoying.

**Comment by Sathya-S3** [comment]
Addressing the sub-issues within this issue:

- TODO: Landing page needs updating.
- The vertical centering of labels in the search table of the search page have been corrected (commit: [b2f1a14](https://github.com/CCP-NC/ccpnc-database/commit/b2f1a1423e944d71b26121fe88d33f0a69b71ec7)).
- The gap between Version and License on the results page has been corrected (commit: [4a29656](https://github.com/CCP-NC/ccpnc-database/commit/4a29656971258d04fea651b35470a488935973d7)).
- DOI is now also displayed on the results page.
- MRD numbers are now searchable (commit: [a1080b2](https://github.com/CCP-NC/ccpnc-database/commit/a1080b24575694b860c56a2b9edb4698560db842)).
- On the search page, the 'Database name' is displayed as a dropdown list, rather than a free-text box (fixed in commit: [06d33d4](https://github.com/CCP-NC/ccpnc-database/commit/06d33d4044acef3363e78e77ec6646c94c283d68)).
- The unit cell formula now appears in both the listed search results page and also the individual search result page (commit: [dbe59c3](https://github.com/CCP-NC/ccpnc-database/commit/dbe59c3d8a97d9183d4ef13609e373669801aedb)).
- The calculation details can be open by a single mouse-click and collapsed by another mouse-click. The display box stays open until the user collapses it (commit: [5b0c0f2](https://github.com/CCP-NC/ccpnc-database/commit/5b0c0f2709f1125dcd44c2272a7451b98a5516ac)).
- TODO: Make the calculation details text selectable for user.

**Comment by Sathya-S3** [comment]
Update:
Commits [d8cd7a3](https://github.com/CCP-NC/ccpnc-database/commit/d8cd7a3452e1c9c0e68bcf1bc01567d5a48444db) and 
[dc253f0](https://github.com/CCP-NC/ccpnc-database/commit/dc253f0f15bd63beb537747c9dded44736db7689) introduce a 'Copy calculation details' button for a cleaner way to copy the calculation metadata details to clipboard without manual drag-and-select from the user side.

Additionally, the calculation metadata is displayed in a cleaner JSON parsed format (commit [45383b9](https://github.com/CCP-NC/ccpnc-database/commit/45383b9e695a141eaaad2ab3eb7120056442600c)).

**Comment by Sathya-S3** [comment]
Closing this issue, as all requests except the landing page update has been completed.
